# Generated by Django 5.1 on 2024-09-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_employee_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
    ]
