# Generated by Django 5.1 on 2024-09-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_reservation_date_remove_reservation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_table',
            field=models.BooleanField(default=False),
        ),
    ]
